#!/usr/bin/env python3
"""
Consolidate all Markdown summaries in monthly/aisummary into monthly/index.html.

Output HTML includes an H1 title: "Model Meter Monthly summaries" and a TOC.
Markdown is rendered client-side via marked.js to avoid Python deps.
"""

from __future__ import annotations

import html
from pathlib import Path
from datetime import datetime

TITLE = "Model Meter Monthly summaries - ✨ AI generated"


def read_markdown_files(aisummary_dir: Path) -> list[tuple[str, str]]:
	"""Return list of (id, markdown_text) sorted descending by id (YYYY-MM-DD)."""
	files = sorted(
		(p for p in aisummary_dir.glob("*.md") if p.is_file()),
		key=lambda p: p.stem,
		reverse=True,
	)
	result: list[tuple[str, str]] = []
	for p in files:
		try:
			text = p.read_text(encoding="utf-8")
		except UnicodeDecodeError:
			text = p.read_text(errors="replace")
		result.append((p.stem, text))
	return result
def build_html(sections: list[tuple[str, str]]) -> str:
	"""Build a single HTML document string styled like the main explorer page."""
	# Escape content for safe embedding inside <script type="text/markdown">.
	section_html: list[str] = []
	for idx, (sid, md) in enumerate(sections):
		# Build human-friendly date label from YYYY-MM-DD, safe on Windows (no %-d)
		try:
			dt = datetime.strptime(sid, "%Y-%m-%d")
			label = f"{dt.day} {dt.strftime('%B %Y')}"  # e.g., 15 March 2016
		except Exception:
			label = sid
		# Use textContent via script tag to keep raw markdown; minimal escaping
		escaped_md = md.replace("</script>", "</scr" + "ipt>")
		is_first = idx == 0
		collapsed_cls = "" if is_first else " collapsed"
		section_html.append(
			f"""
			<article id="{html.escape(sid)}" class="article{collapsed_cls}">
				<div class="month-content">
					<div class=\"markdown-body\">
						<script type=\"text/markdown\">{escaped_md}</script>
					</div>
				</div>
			</article>
			"""
		)

	# HTML template using the same tokens and overall look as index.html
	html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>{html.escape(TITLE)}</title>
	<link rel="stylesheet" href="../site.css">
	<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
	<base target="_self">
	<meta name="color-scheme" content="light dark">
	<meta name="theme-color" content="#087f6b">
	<link rel="icon" type="image/png" href="../img/favicon.png">
    
</head>
<body class="summary-page archive-page">
	<div class="container">
		<div class="card">
			<div class="card-hd">
				<div class="title"><a href="../index.html" class="brand">Model Meters</a></div>
				<nav class="workspace-nav" aria-label="Main navigation">
					<a href="../index.html">Microsoft Foundry</a>
					<a href="../github/index.html">GitHub Meters</a>
					<a href="../agent/" aria-current="page"><span class="ui-icon icon-sparkles" aria-hidden="true"></span>AI Summaries</a>
				</nav>
				<button id="btn-theme" class="icon-button" title="Toggle light/dark mode" aria-label="Toggle light/dark mode"><span class="ui-icon icon-moon" aria-hidden="true"></span></button>
			</div>
			<div class="workspace-heading">
				<div><span class="eyebrow">Pricing intelligence</span><h1>Monthly summary archive</h1></div>
				<div class="toolbar">
					<button id="btn-back" title="Back to Model Meters"><span class="ui-icon icon-back" aria-hidden="true"></span>Model Meters</button>
				</div>
			</div>
			<div class="content">
				<section class="articles">
					{''.join(section_html)}
				</section>
			</div>
			<div class="footer">Generated by consolidate-ai-summaries.py</div>
		</div>
	</div>

	<script>
		// Theme toggle (match main index.html behavior exactly)
		(function initTheme(){{
			const root = document.documentElement;
			const btn = document.getElementById('btn-theme');
			if(!btn) return; // safety
			// Prefer explicit ?theme= in URL; else fall back to stored preference
			const urlTheme = new URLSearchParams(window.location.search).get('theme');
			if (urlTheme === 'dark' || urlTheme === 'light') {{
				if (urlTheme === 'dark') root.setAttribute('data-theme','dark'); else root.removeAttribute('data-theme');
				localStorage.setItem('priceExplorerTheme', urlTheme);
			}} else {{
				const stored = localStorage.getItem('priceExplorerTheme');
				if (stored === 'dark') root.setAttribute('data-theme','dark');
			}}
			function currentMode(){{ return root.getAttribute('data-theme') === 'dark' ? 'dark' : 'light'; }}
			function updateBtn(){{
				const mode = currentMode();
				btn.innerHTML = `<span class="ui-icon icon-${{mode === 'dark' ? 'sun' : 'moon'}}" aria-hidden="true"></span>`;
				btn.setAttribute('aria-pressed', mode==='dark');
				btn.title = 'Switch to ' + (mode==='dark' ? 'light' : 'dark') + ' mode';
				btn.setAttribute('aria-label', btn.title);
			}}
			btn.addEventListener('click', ()=> {{
				const isDark = currentMode()==='dark';
				if (isDark) root.removeAttribute('data-theme'); else root.setAttribute('data-theme','dark');
				localStorage.setItem('priceExplorerTheme', isDark ? 'light':'dark');
				updateBtn();
			}});
			updateBtn();
		}})();
	</script>

	<script>
		// Back button: navigate to parent, preserving theme via ?theme=
		(function(){{
			const btn = document.getElementById('btn-back');
			if (!btn) return;
			btn.addEventListener('click', ()=>{{
				const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
				const theme = isDark ? 'dark' : 'light';
				window.location.href = '../?theme=' + encodeURIComponent(theme);
			}});
		}})();
	</script>

	<script>
		// Render markdown into each article section using marked.js
		document.querySelectorAll('div.markdown-body > script[type="text/markdown"]').forEach((script) => {{
			const container = script.parentElement;
			const raw = script.textContent || '';
			const html = marked.parse(raw, {{ breaks: true, mangle: false, headerIds: true }});
			container.innerHTML = html;
		}});
	</script>

	<script>
		// Collapsible behavior: use the first heading inside each markdown section as the toggle.
		(function(){{
			function ensureDetailsWrapper(article){{
				const body = article.querySelector('.markdown-body');
				if (!body) return {{ heading: null, details: null }};
				let heading = body.querySelector('h1, h2, h3, h4, h5, h6');
				if (!heading) return {{ heading: null, details: null }};
				// Ensure the first heading is level 1 (H1) so all date headers are consistent
				if (heading.tagName.toLowerCase() !== 'h1') {{
					const h1 = document.createElement('h1');
					// Copy attributes
					Array.from(heading.attributes).forEach(attr => h1.setAttribute(attr.name, attr.value));
					// Move children
					while (heading.firstChild) {{ h1.appendChild(heading.firstChild); }}
					body.replaceChild(h1, heading);
					heading = h1;
				}}
				// Wrap all siblings after the first heading into a details container
				let details = body.querySelector('.month-details');
				if (!details) {{
					details = document.createElement('div');
					details.className = 'month-details';
					let node = heading.nextSibling;
					const frag = document.createDocumentFragment();
					while (node) {{
						const next = node.nextSibling;
						frag.appendChild(node);
						node = next;
					}}
					body.insertBefore(details, null);
					details.appendChild(frag);
				}}
				return {{ heading, details }};
			}}

			function setExpanded(article, expanded){{
				const {{ heading }} = ensureDetailsWrapper(article);
				if (expanded) {{
					article.classList.remove('collapsed');
					heading?.setAttribute('aria-expanded','true');
				}} else {{
					article.classList.add('collapsed');
					heading?.setAttribute('aria-expanded','false');
				}}
			}}

			const articles = Array.from(document.querySelectorAll('.articles > .article'));
			articles.forEach((article)=>{{
				const {{ heading }} = ensureDetailsWrapper(article);
				if (!heading) return;
				// Make heading interactive and add chevron cue
				heading.classList.add('month-title');
				heading.setAttribute('role','button');
				heading.setAttribute('tabindex','0');
				// Initial state
				heading.setAttribute('aria-expanded', article.classList.contains('collapsed') ? 'false' : 'true');

				heading.addEventListener('click', ()=> setExpanded(article, article.classList.contains('collapsed')));
				heading.addEventListener('keydown', (e)=>{{
					if (e.key === 'Enter' || e.key === ' ') {{ e.preventDefault(); heading.click(); }}
				}});
			}});

			// If URL has a hash matching an article id, expand that one and collapse others.
			const id = decodeURIComponent(location.hash || '').replace('#','');
			if (id) {{
				articles.forEach(a => setExpanded(a, a.id === id));
			}}
		}})();
	</script>
</body>
</html>
"""
	return html_doc


def main() -> int:
	repo_root = Path(__file__).resolve().parent
	monthly_dir = repo_root / "monthly"
	aisummary_dir = monthly_dir / "aisummary"
	if not aisummary_dir.exists():
		raise SystemExit(f"Directory not found: {aisummary_dir}")

	sections = read_markdown_files(aisummary_dir)
	if not sections:
		raise SystemExit("No markdown files found in monthly/aisummary")

	html_text = build_html(sections)
	out_file = monthly_dir / "index.html"
	out_file.write_text(html_text, encoding="utf-8")
	print(f"Wrote {out_file} with {len(sections)} sections.")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())

